mysite/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings



urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^cats/$', views.detailCats, name='detailCats'),
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
	url(r'^question/$', views.QuestionList.as_view(), name='api-questions'),
	url(r'^cat/$', views.CatList.as_view(), name='api-cats')
]

polls/models.py
# -*- coding: utf-8 -*-
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'
	
class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text

class Cat(models.Model):
	name = models.CharField(max_length=100)
	description = models.CharField(max_length=250)
	image = models.ImageField("avatar", upload_to="avatar", blank= True, null =True)

	def __str__(self):
		return self.name 
	

polls/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse,HttpResponseRedirect
from .models import Question,Cat,Choice
from .serializers import QuestionSerializer, CatSerializer
from django.http import Http404
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.shortcuts import get_object_or_404,render
from django.core import serializers
import json
from rest_framework import generics, filters
from rest_framework.permissions import AllowAny

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def detailCats(request):
	cat_list = Cat.objects.order_by('-name')
	context = {'cat_list': cat_list}
	return render(request, 'polls/detailCats.html', context)

class QuestionList(generics.ListAPIView):
    serializer_class    = QuestionSerializer
    permission_classes  = (AllowAny,)
    filter_backends     = (filters.DjangoFilterBackend,)

    def get_queryset(self):
        queryset = Question.objects.all()
        return queryset

class CatList(generics.ListAPIView):
    serializer_class    = CatSerializer
    permission_classes  = (AllowAny,)
    filter_backends     = (filters.DjangoFilterBackend,)

    def get_queryset(self):
        queryset = Cat.objects.all()
        return queryset


     

polls/templates/base_site.html
{% extends "admin/base.html" %}

{% block title %}{{ title }} | {{ site_title|default:_('Django site admin') }}{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">Polls Administration</a></h1>
{% endblock %}

{% block nav-global %}{% endblock %}

polls/templates/polls/detail.html
{% extends 'polls/index.html' %}
{% block content %}
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

{% endblock %}

polls/templates/polls/detailCats.html
{% extends 'polls/index.html' %}
{% load static %}
{% block content %}
	{% if cat_list %}  
	    
	    <div class="section">
		    <div class="row">
		    	<div class="col s12" style="background-color: #ccc">
		    		<div class="section">
		    			{% for cat in cat_list %}
		    			<div class="col s12 m12 l4">
		    				
							<div class="card large">
								<div class="card-image">
									<img src="{{cat.image.url}}">
									<span class="card-title">{{cat.name}}</span>
								</div>
								<div class="card-content">
									<p>{{cat.description}}</p>
								</div>
								<div class="card-action">
									<a href="#">This is a link</a>
								</div>
							</div>
		    			</div>	


						
						{% endfor %}

		    		</div>
		    	</div>
		    	
		    </div>
	    </div>		

		
	{% else %}
    	<p>No cats are available.</p>
	{% endif %}
{% endblock %}

polls/templates/polls/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<!-- <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.theme.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.theme.min.css.map' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css.map' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'js/bootstrap.min.js' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'js/npm.js' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'js/glyphicons-halflings-regular.eot' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'js/glyphicons-halflings-regular.svg' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'js/glyphicons-halflings-regular.ttf' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'js/glyphicons-halflings-regular.woff' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'js/glyphicons-halflings-regular.woff2' %}"> -->
	<link rel="stylesheet" type="text/css" href="{% static 'materialize/css/materialize.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'materialize/js/materialize.min.js' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'materialize/roboto/Roboto-Bold.woff' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'materialize/roboto/Roboto-Bold.woff2' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'materialize/roboto/Roboto-Light.woff' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'materialize/roboto/Roboto-Light.woff2' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'materialize/roboto/Roboto-Medium.woff' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'materialize/roboto/Roboto-Medium.woff2' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'materialize/roboto/Roboto-Regular.woff' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'materialize/roboto/Roboto-Regular.woff2' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'materialize/roboto/Roboto-Bold.Thin' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'materialize/roboto/Roboto-Bold.Thin2' %}">






</head>
<body>

	<div class="container">
		{% block content %}
			{% if latest_question_list %}
			    <ul class="collection with-header">
			    <li class="collection-header"><h4>Lista de Preguntas</h4></li>
			    {% for question in latest_question_list %}
			        <a class="collection-item" href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
			    {% endfor %}
			    </ul>
			{% else %}
		    	<p>No polls are available.</p>
			{% endif %}
		{% endblock %}
	</div>
</body>
</html>

polls/templates/polls/results.html
{% extends 'polls/index.html'%}

{% block content %}
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}